# This script extracts DFT energies from an optimization output file and plots the energy convergence.
# It assumes that the output file contains lines with the format "Total DFT energy: <value>".
# The energies are extracted, converted from Hartree to eV, and then plotted using Matplotlib.
# Note: Ensure that the file "optimizacion.out" is in the same directory as this script or provide the correct path.
# The script uses regular expressions to robustly extract the energy values, even if there are variations in formatting.
# Make sure to have Matplotlib installed in your Python environment to run this script successfully. You can install it using pip if you haven't already:
# pip install matplotlib
# The plot will show the energy convergence over the optimization steps, which can help in analyzing the optimization process and determining if it has converged to a minimum energy configuration.
# The script also includes error handling to warn if an energy value cannot be extracted from a line, which can help in debugging the output file format.
# The energies are stored in a list and plotted as blue circles connected by lines, with appropriate labels and grid for better visualization.
# Make sure to adjust the file name and path as needed, and ensure that the output file contains the expected energy lines for the script to work correctly.
# The script can be further enhanced by adding features such as saving the plot to a file, allowing for command-line arguments to specify the input file, or adding more detailed error handling and logging.
# Overall, this script provides a simple yet effective way to analyze the energy convergence of a DFT optimization process by extracting and plotting the energies from the output file.
# This script is intended for educational and analytical purposes, and can be modified to suit specific needs or to handle different output formats as required.
# Please ensure that you have the necessary permissions to read the output file and that it is formatted correctly for the script to function as intended.
# Note: The conversion factor from Hartree to eV is approximately 27.2114, which is used in the script to convert the extracted energies for plotting.
# The script assumes that the energies are listed in the output file in a consistent format, and it uses regular expressions to extract the numerical values, which allows for some flexibility in the formatting of the energy lines.
# The plot generated by this script will help visualize the energy convergence during the optimization process, which is crucial for understanding the behavior of the system being studied and for determining if the optimization has successfully reached a minimum energy configuration.
# The script can be easily modified to handle different output formats or to extract additional information as needed, making it a versatile tool for analyzing DFT optimization results.
# The script is designed to be straightforward and easy to use, allowing users to quickly analyze their optimization results without needing to manually extract and plot the energies.
# The script can be further enhanced by adding features such as saving the plot to a file, allowing for command-line arguments to specify the input file, or adding more detailed error handling and logging. 
import re
import matplotlib.pyplot as plt

energies_ha = [] # Energies in Hartree

with open("optimizacion.out", "r") as f:
    for line in f:
        if "Total DFT energy" in line:
            # Use regex to extract the first valid floating-point number
            match = re.search(r"[-+]?\d*\.\d+|\d+", line)
            if match:
                energy = float(match.group())
                energies_ha.append(energy)
            else:
                print(f"Warning: Could not extract energy from line: {line.strip()}")

# Convert Hartree to eV (optional, ASE uses eV by default)
energies_ev = [e * 27.2114 for e in energies_ha]

# Convert Hartree to eV (optional, ASE uses eV by default)
energies_ev = [e * 27.2114 for e in energies_ha]
print(energies_ev)
# Create plot
plt.figure(figsize=(8, 5))
plt.plot(energies_ev, 'bo-', markersize=5, label="DFT Energy (eV)")
# Customize plot
plt.xlabel("Optimization Step", fontsize=12)
plt.ylabel("Energy (eV)", fontsize=12)
plt.title("DFT Energy Convergence", fontsize=14)
plt.grid(True, linestyle='--', alpha=0.7)
plt.legend()

plt.show()